### ISSUE TITLE
CMake/Makefile support

### ISSUE THREAD

**Issue by chances** [fuzzybinary/dart_shared_libray#5]
I'm interested in experimenting with this library.

Would you accept a PR to add a CMake and/or Makefile conversion of your Genie script?

**Comment by fuzzybinary** [comment]
Yes. I mostly used Genie because I"m familiar with it and got overly frustrated with both gn and Bazel (which would have potentially allowed me to build the dart_lib file directly).

I would aim for CMake over make as it seems to be more supported and because it allows project generation in places where it's not directly supported.

**Comment by fuzzybinary** [comment]
As much as I like it, one major problem with GENie is it's non-standard and has a low user base, so some of the features that don't see large use tend to decay over time (and I'm sure Make support is one of them).

In reality, supporitng something more standard like CMake is the better option long term.

**Comment by fuzzybinary** [comment]
Hi @chances,

I've added CMake support for Windows and Linux. Mac will come a bit later. Do you want to try it out and see if it works for you?

**Comment by fuzzybinary** [comment]
All platforms should be supported now. I'm sure there's lots of optimizations / improvements that can be done but we can open individual bugs for those when needed.
